language: node_js
node_js:
  - 'node'

branches:
  only:
  - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod


deploy:
  provider: heroku
  api_key:
    secure: "062796eb-74a5-451b-9c87-40e35e50c5ed"
  app: angular_deploy_git
